#!/usr/bin/env python3
"""
generate_voice_data.py (v2)

Converts all voice_*.wav files in a folder into a single Arduino header: voice_data.h

- Forces mono
- Converts to 16-bit PCM
- Resamples to 16 kHz (matches your ESP32 I2S settings)
- Stores audio as PROGMEM byte arrays: const uint8_t voice_x[] PROGMEM = {...}
- Adds length constants: const size_t voice_x_len = sizeof(voice_x);
- Adds availability macros for safe optional use in sketches:
    #define HAS_VOICE_voice_x 1

Install once:
  pip install numpy soundfile

Run:
  python generate_voice_data.py voices
"""
import sys
from pathlib import Path
import numpy as np
import soundfile as sf

TARGET_SR = 16000

def resample_linear(data: np.ndarray, sr: int) -> np.ndarray:
    if sr == TARGET_SR:
        return data
    ratio = TARGET_SR / float(sr)
    x_old = np.linspace(0.0, 1.0, num=len(data), endpoint=True)
    x_new = np.linspace(0.0, 1.0, num=int(len(data) * ratio), endpoint=True)
    return np.interp(x_new, x_old, data).astype(np.float32)

def load_wav_as_pcm16(path: Path) -> np.ndarray:
    data, sr = sf.read(path, dtype="float32", always_2d=False)
    if getattr(data, "ndim", 1) > 1:
        data = data[:, 0]  # take left channel
    data = resample_linear(np.asarray(data, dtype=np.float32), sr)
    pcm = np.clip(data * 32767.0, -32768.0, 32767.0).astype(np.int16)
    return pcm

def main(folder: str) -> None:
    in_dir = Path(folder)
    wavs = sorted(in_dir.glob("voice_*.wav"))
    if not wavs:
        print("❌ No voice_*.wav files found in:", in_dir.resolve())
        sys.exit(2)

    out_lines = []
    out_lines.append("#pragma once")
    out_lines.append("#include <Arduino.h>")
    out_lines.append("")
    out_lines.append("// Auto-generated by generate_voice_data.py (v2)")
    out_lines.append(f"// Source folder: {in_dir.resolve()}")
    out_lines.append("// Target format: mono, 16-bit PCM, 16 kHz")
    out_lines.append("")

    # Availability macros
    for wav in wavs:
        name = wav.stem
        out_lines.append(f"#define HAS_VOICE_{name} 1")
    out_lines.append("")

    for wav in wavs:
        name = wav.stem
        pcm = load_wav_as_pcm16(wav)

        out_lines.append(f"// {wav.name}")
        out_lines.append(f"const uint8_t {name}[] PROGMEM = {{")

        row = []
        for b in pcm.tobytes():
            row.append(f"0x{b:02X}")
            if len(row) == 16:
                out_lines.append("  " + ", ".join(row) + ",")
                row.clear()
        if row:
            out_lines.append("  " + ", ".join(row) + ",")

        out_lines.append("};")
        out_lines.append(f"const size_t {name}_len = sizeof({name});")
        out_lines.append("")

    Path("voice_data.h").write_text("\n".join(out_lines), encoding="utf-8")
    print(f"✅ Generated voice_data.h with {len(wavs)} clips.")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python generate_voice_data.py <folder_with_wavs>")
        sys.exit(1)
    main(sys.argv[1])
